name: box_shadow_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build_config: ^1.1.1
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.18.2+1
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_bloc: ^8.1.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
