name: box_shadow_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build_config: ^1.1.1
  dartz: ^0.10.1
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.5
  flex_color_picker: ^3.2.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hydrated_bloc: ^9.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  network_info_plus: ^4.0.1
  path: ^1.8.2
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: ^2.1.8
  flutter_bloc: ^8.1.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  generate: true
